### ISSUE TITLE
Gold Coins not detected

### ISSUE THREAD

**Issue by N-Montana** [shiftthedev/Coin-Pouch#5]
I've just updated the mod to 1.5.2 in my custom version of VH that I host on a server and have been informed that Gold Coins aren't functioning correctly.

![image](https://github.com/user-attachments/assets/409b51a2-07b5-4d6a-b385-30b369477ea0)
![image2](https://github.com/user-attachments/assets/564e0a8c-2ce6-435d-a686-9413886b9c6d)
![image3](https://github.com/user-attachments/assets/e243c803-741e-4611-bb48-48b05db30076)

As you can see in the screenshots gold coins are not registered by the tooltip or stations. There's also been a reported crash when opening the Artisan Table, however I've yet to test this and am unaware if it is related.

**Comment by shiftthedev** [comment]
are you using VaultFaster? if so make sure its updated.
otherwise i'll need a server log, a client log of someone with the gold coin issue, a crash-report from that crash and a list of extra mods.

**Comment by N-Montana** [comment]
Yep, I have Vault Faster but it was already the latest version (2.1.1).

The complete modlist (other mods have been updated and I can't remember exactly what's different now): [modlist.txt](https://github.com/user-attachments/files/17144837/modlist.txt)
And my log from loading and logging in: [latest.log](https://github.com/user-attachments/files/17145247/latest.log)

There's an unrelated bug that's causing a lot of repeating errors that I've excluded as the file gets rather large, it's happened before updating though. I've been unable to reproduce the crash and assume it's simply a client issue from updating rather than anything problematic. I'll try and look into it when they're online later.

The server log: [latest.log](https://github.com/user-attachments/files/17145283/latest.log)

**Comment by shiftthedev** [comment]
I can't seem to be able to replicate this issue.
When you can, try it in single-player. I'd like to know if it's a server only issue or not.

**Comment by N-Montana** [comment]
Just tried it in singleplayer and realised that vault gold itself doesn't exist, I'm not actually sure this is your mods fault...

![image](https://github.com/user-attachments/assets/da306314-3f23-4f24-9ac3-79cd78d993b7)

I'm not even sure how or why this has happened I'll keep looking into it. Apologies literally hadn't even noticed it was missing.

**Comment by N-Montana** [comment]
Okay, I just did some more tests and reverting back to 1.4.6 of coin pouch does fix the issue, including the crash that was happening (although it was only on 1 client of 4 tested). Since you were unable to reproduce the issue if you'd like the pack is uploaded [here](https://drive.google.com/file/d/1sO4AMwcOvGMgGtn_rkvU6DsxrOYfOX2M/view?usp=drive_link) this is the active version with 1.4.6 but if you were to change it the bug(s) should happen.

**Comment by shiftthedev** [comment]
fixed in [1.5.3](https://www.curseforge.com/minecraft/mc-mods/coin-pouch-vault-hunters-addon/files/5759445)
if it persist will re-open this issue.

**Comment by N-Montana** [comment]
Excellent thank you so much!
